trigger:
  - master
  - development

pr:
  - master
  - development

#variables:
#  npm_config_cache: $(Pipeline.Workspace)/.npm

resources:
  repositories:
    - repository: templates
      type: git
      name: Core/build-templates
      #ref: refs/tags/v1.3

jobs:
  - template: react-yarn-app-deployment.yaml@templates
